@startuml

[*] --> TurnOff : 初期状態に遷移

TurnOff --> TurnOff : 無操作時
TurnOff --> [*] : クリア
TurnOff : 通常消灯

TurnOff --> TurnOn : 通常点灯
TurnOn --> TurnOff : 通常消灯
TurnOn --> [*] : クリア
TurnOn : 通常点灯

TurnOff --> Flashing : 点滅
Flashing --> TurnOff : 通常消灯
Flashing --> [*] : クリア
Flashing : 点滅

TurnOff --> IntensityChg : 強度変更
IntensityChg --> TurnOff : 通常消灯
IntensityChg --> [*] : クリア
IntensityChg : 強度変更

@enduml